generator:
  class:                   sfPropelAdminGenerator
  param:
    model_class:           sfJob
    theme:                 default

    fields:
      tries:               { name: Number of tries }
      created_at:          { name: Created at, params: date_format=MM/dd HH:mm }
      scheduled_at:        { name: Scheduled at, params: date_format=MM/dd HH:mm }
      last_tried_at:       { name: Last tried at, params: date_format=MM/dd HH:mm }
      completed_at:        { name: Completed at, params: date_format=MM/dd HH:mm }

    list:
      title:               List of the Job
      filters:             [type, status, sf_job_queue_id]
      sort:                [created_at, desc]
      display:             [sf_job_queue, =type, =name, _status, _tries, _is_recuring, created_at, scheduled_at, last_tried_at, completed_at]
      object_actions:
        _edit:             -
        cancel:            { name: Cancel job, action: cancel, icon: /sf/sf_admin/images/delete.png }
        run:               { name: Run job, action: run, icon: /sf/sf_admin/images/next.png, confirm: "Please be aware that it may take several minutes until this action will finish. If the job to be runned is huge, it may overload your webserver. In this case, you will prefer to run this job using the asynchronous job queue manager." }
      actions:
        _create:           -
        job_queues_list:   { name: Back to job queues list, action: listQueues, icon: /sf/sf_admin/images/list.png }

    edit:
      title:               Job edition
      display:
        "Job informations": [sf_job_queue_id, _type, max_tries, is_recuring, retry_delay, scheduled_at]
        "Job parameters":   [_params]
        "Job status":       [status, tries, created_at, last_tried_at, completed_at]
      fields:
        status:             { type: plain }
        tries:              { type: plain }
        created_at:         { type: plain }
        last_tried_at:      { type: plain }
        completed_at:       { type: plain }