<?php
// auto-generated by sfPropelAdmin
// date: 2007/10/21 16:47:13
?>
<?php use_helper('I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<?php if (isset($filters['sf_job_queue_id']) && $filters['sf_job_queue_id'] !== ''): ?>
  <h1>
    <?php
    echo __('List of the jobs in the job queue "%1%"',
            array('%1%' => $sf_job_queue->getName()))
    ?>
  </h1>
<?php else: ?>
  <h1><?php echo __('List of the jobs', array()) ?></h1>
<?php endif; ?>

<div id="sf_admin_header">
<?php include_partial('sfJob/list_header', array('pager' => $pager)) ?>
<?php include_partial('sfJob/list_messages', array('pager' => $pager)) ?>
</div>

<div id="sf_admin_bar">
<?php include_partial('filters', array('filters' => $filters)) ?>
</div>

<div id="sf_admin_content">
<?php if (!$pager->getNbResults()): ?>
<?php echo __('no result') ?>
<?php else: ?>
<?php include_partial('sfJob/list', array('pager' => $pager)) ?>
<?php endif; ?>
<?php include_partial('list_actions') ?>
</div>

<div id="sf_job_logs">&nbsp;</div>

<div id="sf_admin_footer">
<?php include_partial('sfJob/list_footer', array('pager' => $pager)) ?>
</div>

</div>
